relativeURLs = true
baseURL = "https://kkarthik23.github.io/"
title = "Hugo"
author = "kk"
copyright = "Copyright © 2008–2019, kk and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
